# This docker-compose file is intended for local development.
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      # Mount the backend code for live reloading
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount the frontend code for live reloading
      - ./frontend:/app
      # Keep the installed packages in a separate volume
      - /app/node_modules
    environment:
      # This ensures that Next.js hot-reloading works correctly inside Docker
      - CHOKIDAR_USEPOLLING=true
      # The frontend, running in the user's browser, needs to connect to the backend
      # via localhost. The container's internal network address (`http://backend:8000`)
      # is not accessible from the browser.
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

networks:
  default:
    driver: bridge
